### ISSUE TITLE
Feature: generate multiple outputs from one template file

### ISSUE THREAD

**Issue by kalitine** [chocolateboy/parcel-plugin-nunjucks#18]
In my case, I want to generate multiple outputs from one template file by specifying different nunjucks configurations. Each configuration file represents the same content but in different languages. Is it possible to achieve with the current v1.1.0 or not?

**Comment by chocolateboy** [comment]
I think the best way to do this would be with a build step, possibly using nunjucks to generate the variants via one of its wrappers, e.g.:

- https://www.npmjs.com/package/grunt-nunjucks
- https://www.npmjs.com/package/gulp-nunjucks
- https://www.npmjs.com/package/nj-cli
- https://www.npmjs.com/package/njk
- https://www.npmjs.com/package/njk-cli
- https://www.npmjs.com/package/nunjucks-cli

Note that if you want the generated variants to (also) be nunjucks templates i.e. using nunjucks templates to generate nunjucks templates, the delimiters in the source template(s) can be [customized](http://mozilla.github.io/nunjucks/api.html#customizing-syntax) to distinguish them from the delimiters in the target templates. Or you can use the [`{% raw %}`](https://mozilla.github.io/nunjucks/templating.html#raw) (AKA [`{% verbatim %}`](https://mozilla.github.io/nunjucks/templating.html#verbatim)) tags as suggested [here](https://github.com/mozilla/nunjucks/issues/969#issuecomment-340286513).
