### ISSUE TITLE
Can't make it work on codesandbox.io?

### ISSUE THREAD

**Issue by maximelebreton** [chocolateboy/parcel-plugin-nunjucks#23]
Hello @chocolateboy.

I don't understand why I can't make your plugin works on codesandbox.io, any ideas?

https://codesandbox.io/s/suspicious-leavitt-lqcpl

Thank you!

**Comment by chocolateboy** [comment]
It works fine for me locally. I suggest developing locally, or you could take it up on the [CodeSandbox repo](https://github.com/codesandbox/codesandbox-client). It appears to have [several issues](https://github.com/codesandbox/codesandbox-client/search?q=parcel&type=Issues) with its Parcel environment.
