### ISSUE TITLE
Styles are included only in single page while extending template

### ISSUE THREAD

**Issue by uNmAnNeR** [chocolateboy/parcel-plugin-nunjucks#27]
**Environment**

https://github.com/uNmAnNeR/flashrepair-fe/blob/master/package.json
- Node.js version:  v12.8.0 
- OS: Win 10 x64

**Describe the bug**

here is my project starter
styles is included in js, and js is included in layout.
There are 2 pages extend layout. Javascript is appeared on both, but style included only on one of pages.

**Expected behavior**

Style should be included in every page which extends layout.

**To reproduce**

https://github.com/uNmAnNeR/flashrepair-fe/

`npm start`
check styling

**Comment by chocolateboy** [comment]
This isn't a parcel-plugin-nunjucks issue. The result is the same if nunjucks isn't used e.g.: https://github.com/chocolateboy/flashrepair-fe/tree/strip-nunjucks

**Comment by uNmAnNeR** [comment]
@chocolateboy thanks! hm, let me ask parcel team

**Comment by chocolateboy** [comment]
Possibly related: https://github.com/parcel-bundler/parcel/issues/2340

**Comment by uNmAnNeR** [comment]
@chocolateboy definitely it is. And it is so old... thanks anyway for clearing up
