### ISSUE TITLE
syncPromise is not working

### ISSUE THREAD

**Issue by trave** [chocolateboy/parcel-plugin-nunjucks#28]
**Environment**

- parcel-plugin-nunjucks version: v2.1.1
- Parcel version: v1.12.4
- nunjucks version: v3.2.0
- Node.js version: v12.12.0
- OS: macOS (Mojave 10.14.6)

**Describe the bug**

Parcel starts `⠋ Building...` and wait forever. After research i found that `syncPromise(asset.getConfig(...CONFIG_FILE)) || {}` in `node_modules/parcel-plugin-nunjucks/dist/NunjucksAsset.js` is never ends.

As i see this behaviour already described in https://github.com/parcel-bundler/parcel/issues/3566

**Expected behavior**

Parcel build the project.

**To reproduce**

1. Use NodeJS 12.12.0 and minimal Parcel project from README.md
2. Add `parcel-plugin-nunjucks` to `package.json` file
3. Execute `npx parcel build` and wait forever...

**Comment by chocolateboy** [comment]
Thanks for the prompt. Should be fixed in the next release.

**Comment by trave** [comment]
Really fast! Thx a lot!
